<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200415185255 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE TABLE email_message (id UUID NOT NULL, sender TEXT DEFAULT NULL, to_recipient TEXT DEFAULT NULL, about TEXT DEFAULT NULL, text TEXT DEFAULT NULL, date_received TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, attachment BOOLEAN DEFAULT \'false\', PRIMARY KEY(id))');


//        $this->addSql('insert into email_message (id,
//                           sender,
//                           to_recipient,
//                           about,
//                           text,
//                           attachment,
//                           date_received) VALUES ( \'eebf79c2-fbdb-4bcd-65fe-9d8bd8916a15\',
//                                  \'yalagin@gmail.com\',
//                                   \'testing@gmail.com\',
//                                  \'the subject of email might be long like Lorem ipsum\',
//                                   \'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. \',
//                                   \'true\',
//                                   \'2020-04-15T13:47:26.154Z\');');
//
//        $this->addSql('insert into email_message (id,
//                           sender,
//                           to_recipient,
//                           about,
//                           text,
//                           date_received) VALUES ( \'eebf71c2-fbdb-4bcd-65fe-9d8bd8916a15\',
//                                  \'MaximYalagin@gmail.com\',
//                                   \'secondTest@gmail.com, thirdTest@gmail.com, ddd@gmail.com, aaa@gmail.com\',
//                                  \'the subject of email might be long like Lorem ipsum or even more\',
//                                   \'ed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? \',
//                                   \'2020-01-15T13:47:26.154Z\');');
//
//        $this->addSql('insert into email_message (id,
//                           sender,
//                           to_recipient,
//                           about,
//                           text,
//                           attachment,
//                           date_received) VALUES ( \'eebf21c2-fbdb-4bcd-65fe-9d8bd8916a15\',
//                                  \'MaximYalagin@gmail.com\',
//                                   \'thirdTest@gmail.com, ddd@gmail.com, aaa@gmail.com\',
//                                  \'third msg!\',
//                                   \'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. \',
//                                   \'true\',
//                                   \'2020-01-11T13:47:26.154Z\');');

        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'39dbabcb-5007-48ba-8b4d-4d42c3648b7e\', \'tesing@gmail.com\', \'ddd@gmail.com, aaa@gmail.com\', \'third msg!\', \'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. \', \'2020-01-11 13:47:26\', true);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'eebf21c2-fbdb-4bcd-65fe-9d8bd8916a15\', \'MaximYalagin@gmail.com\', \'thirdTest@gmail.com, ddd@gmail.com, aaa@gmail.com\', \'third msg!\', \'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. \', \'2020-01-11 13:47:26\', true);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'ef50f460-95ab-4608-8757-d53649cc5796\', \'yalagin@gmail.com\', \'testing@gmail.com\', \'the subject of email might be long like Lorem ipsum\', \'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. \', \'2020-04-15 13:47:26\', true);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'eebf71c2-fbdb-4bcd-65fe-9d8bd8916a15\', \'MaximYalagin@gmail.com\', \'secondTest@gmail.com, thirdTest@gmail.com, ddd@gmail.com, aaa@gmail.com\', \'the subject of email might be long like Lorem ipsum or even more\', \'ed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? \', \'2020-01-15 13:47:26\', false);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'2eb41fcc-f350-4a4d-b422-4436bfe3c707\', \'instagram@gmail.com\', \'secondTest@gmail.com, ddd@gmail.com, aaa@gmail.com\', \'the subject of email might be long like Lorem ipsum or even more\', \'ed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? \', \'2020-01-15 13:47:26\', false);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'eebf79c2-fbdb-4bcd-65fe-9d8bd8916a15\', \'yalagin@gmail.com\', \'testing@gmail.com\', \'the subject of email might be long like Lorem ipsum\', \'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. \', \'2020-04-15 13:47:26\', true);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'1bde4a96-3092-4a7d-b672-197b252e801c\', \'ddd@fff.com\', \'ddd@fff.com, \', \'string\', \'string\', \'2020-04-18 21:14:05\', true);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'5f77e2d8-c937-4495-801f-b8ca62bd2bdc\', \'tesing@gmail.com\', \'ddd@gmail.com, aaa@gmail.com\', \'third msg!\', \'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. \', \'2020-01-11 13:47:26\', true);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'896485d4-1b14-49a7-8b1d-fe4f7c1bc05d\', \'MaximYalagin@gmail.com\', \'thirdTest@gmail.com, ddd@gmail.com, aaa@gmail.com\', \'third msg!\', \'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. \', \'2020-01-11 13:47:26\', true);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'287206e6-4cf3-4bf8-ac86-084df074f244\', \'yalagin@gmail.com\', \'testing@gmail.com\', \'the subject of email might be long like Lorem ipsum\', \'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. \', \'2020-04-15 13:47:26\', true);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'326c7e3b-ebff-4f9a-b8b4-82f8055ee7a6\', \'MaximYalagin@gmail.com\', \'secondTest@gmail.com, thirdTest@gmail.com, ddd@gmail.com, aaa@gmail.com\', \'the subject of email might be long like Lorem ipsum or even more\', \'ed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? \', \'2020-01-15 13:47:26\', false);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'4918144a-542f-4280-99c1-4342da382313\', \'instagram@gmail.com\', \'secondTest@gmail.com, ddd@gmail.com, aaa@gmail.com\', \'the subject of email might be long like Lorem ipsum or even more\', \'ed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? \', \'2020-01-15 13:47:26\', false);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'5a7d75d7-b6e3-4726-b451-346b0a1d0b73\', \'yalagin@gmail.com\', \'testing@gmail.com\', \'the subject of email might be long like Lorem ipsum\', \'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. \', \'2020-04-15 13:47:26\', true);');
        $this->addSql('INSERT INTO public.email_message (id, sender, to_recipient, about, text, date_received, attachment) VALUES (\'71a9476e-ebd1-4a04-a61d-1b71e90f07ce\', \'ddd@fff.com\', \'ddd@fff.com, \', \'string\', \'string\', \'2020-04-18 21:14:05\', true);');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE email_message');
    }
}
